### ISSUE TITLE
Upgrade to reakit 1.x?

### ISSUE THREAD

**Issue by joshball** [fannypackui/fannypack#82]
Is there a plan (i.e. document or discussion someplace) in place to upgrade to `reakit 1.x`?

I did a [bit of searching](https://github.com/fannypackui/fannypack/issues?utf8=%E2%9C%93&q=reakit+1) in the issues, but didn't see anything. I realize things are still a bit volatile, as they just [released a beta version](https://www.npmjs.com/package/reakit/v/1.0.0-beta.0).

Since they pulled `styled-components`, (https://reakit.io/docs/styling/), and are [using an **experimental** system feature](https://reakit.io/docs/get-started/#default-styles), this seems like a significant change. 

Here is the [migration guide](https://github.com/reakit/reakit/issues/350).

**Comment by jxom** [comment]
Hey! 

There sure is a plan to migrate to Reakit v1. I just wanted the initial release of the beta to sit for a short period before I start writing a migration document/path. 
I’ll be planning to start this process in the next couple of weeks. 

I’ll first post an issue which will list out the things that need to be done to make this happen & we would love for anyone to have input!

**Comment by diegohaz** [comment]
I'll be glad to help on this. It's completely possible to keep fannypack API using Reakit v1. Even though many things should be re-created, others should be easier (like `DialogModal`). Here's an example of how flexible the v1 API is: https://reakit.io/docs/tooltip/#abstracting

I don't recommend relying on `reakit-system-*` packages for now since they're experimental and I don't expect them to be stable so soon. On the other hand, despite being in beta, the `reakit` package is pretty stable right now. It's unlikely that it'll have drastic changes until the final release.

That said, I think it's really valuable for the community that fannypack exists. Thank you. ❤️

**Comment by jxom** [comment]
Hey @diegohaz,

Yeah of course, I think a few components definitely will need to be re-written. I'd love to strip out some of Fannypack's logic/components for some of Reakit's new logic/components (such as Menu, VisuallyHidden, etc), however, some new functionalities & components will need to be implemented (such as the Overlay, Sidebar, Field, typography components, etc).

Early next week, I'll create an issue of a detailed migration path to Reakit v1 which I'd love to get some feedback on. Hopefully we can easily incrementally migrate to v1! I think we can achieve a Reakit v0 to v1 migration without changing Fannypack's API or breaking anything (hopefully).
